# Use an official nginx image as the base
FROM nginx:alpine

# Copy the contents of the src directory to the nginx html directory
COPY app /usr/share/nginx/html

# Expose port 80 to be accessible from outside the container
EXPOSE 80
